FROM ubuntu:22.04

# Switch to apt noninteractive
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles
ENV LANGUAGE=en_US.en
ENV LC_ALL=C

# General development tools
RUN apt update \
	&& apt install -y software-properties-common \
	&& apt install -y \
	curl \
	git \
	htop \
	iftop \
	jq \
	net-tools \
	postgresql-client \
	rsync \
	screen \
	slurm \
	vim \
	&& apt autoremove --purge -y \
	&& apt clean -y && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list \
	&& apt update \
	&& apt install -y gh \
	&& apt clean && rm -rf /var/lib/apt/lists/*

ENV NODE_MAJOR=22
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
	&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
	&& apt update && apt install -y nodejs \
	&& apt clean && rm -rf /var/lib/apt/lists/*

# Install additional dependencies
# ...

# Switch back to dialog for user's use of apt
ENV DEBIAN_FRONTEND=dialog

# Add vscode user
RUN groupadd -r vscode && useradd -rs /bin/bash -m -g vscode vscode

COPY .devcontainer/.bashrc-root /root/.bashrc
COPY .devcontainer/.bashrc-user /home/vscode/.bashrc
